spring.datasource.url=jdbc:mysql://localhost:3306/helpdesk
spring.datasource.username=root
spring.datasource.password=2248
server.port=7777
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.results.loading.embed=TRACE

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,\
                             org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration

springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true