spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
server.port=7777
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.results.loading.embed=TRACE

spring.mail.host=${SMTP_HOST}
spring.mail.port=${SMTP_PORT}
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=${SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${SMTP_STARTTLS}

app.backend-base-url=${APP_BACKEND_BASE_URL}
app.email-verification-token-ttl-hours=${EMAIL_VERIFICATION_TTL_HOURS:24}
app.mail-from=${MAIL_FROM}
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=3600000
